import Footer from '@/components/shared/footer/footer';
import ReactQueryProvider from '@/providers/react-query.provider';
import '@/styles/index.less';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
