import Footer from '@/components/shared/footer/footer';
import ReactQueryProvider from '@/providers/react-query.provider';
import '@/styles/globals.css';
import { Providers } from './provider';
import Header from '@/components/shared/header/header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='light'>
      <body>
        <ReactQueryProvider>
          <Header />
          <Providers>{children}</Providers>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
